name: Test Gibbon RTS

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: test-gibbon-rts
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - nightly-2022-12-30
    steps:
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgc-dev libgmp-dev uthash-dev gcc-11
          sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-11 /usr/bin/gcc
      - name: rustup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: checkout
        uses: actions/checkout@v3
      
      - name: Restore OpenCilk directory from cache
        id: opencilk-cache
        uses: actions/cache@v3
        with:
          path: opencilk
          key: ${{ runner.os }}-opencilk-v2.1

      - name: Download and extract OpenCilk (if needed)
        if: steps.opencilk-cache.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/OpenCilk/opencilk-project/releases/download/opencilk/v2.1/opencilk-2.1.0-x86_64-linux-gnu-ubuntu-22.04.tar.gz
          tar -xzf opencilk-2.1.0-x86_64-linux-gnu-ubuntu-22.04.tar.gz
          mv opencilk-2.1.0-x86_64-linux-gnu-ubuntu-22.04 opencilk

      - name: Add OpenCilk to PATH (prepend)
        run: echo "${{ github.workspace }}/opencilk/bin" >> "$GITHUB_PATH"

      # ---- optional sanity check ----
      - name: Verify OpenCilk clang is first in PATH
        run: |
          clang --version
          llvm-ar --version

      - name: build and test
        run: |
          export GIBBONDIR=`pwd`
          cd gibbon-rts/
          make all
          cargo build -v
          cargo test gc_tests1 -- --nocapture --test-threads 1

      - name: build and test (no eager promotion)
        run: |
          export GIBBONDIR=`pwd`
          cd gibbon-rts/
          make clean
          make GCSTATS=1 EAGER_PROMOTION=0
          cargo build -v
          cargo test gc_tests2 -- --nocapture --test-threads 1
